### ISSUE TITLE
please provide examples of expected configuration values

### ISSUE THREAD

**Issue by raymcdermott** [pjstadig/clojurebot#2]
I see you need two items in `clojurebot/clojurebot.core/config.edn`

```Clojure
{
clojurebot.core/token  "what is this??"

clojurebot.core.slack.log/log-channel "what is this??"
}
```

**Comment by raymcdermott** [comment]
I have entered what I consider to be decent values given the names used:

```
./bin/run     
~/dev/oss/clojurebot/clojurebot.core ~/dev/oss/clojurebot
Retrieving cider/cider-nrepl/0.16.0/cider-nrepl-0.16.0.pom from clojars
Retrieving org/tcrawley/dynapath/1.0.0/dynapath-1.0.0.pom from central
Retrieving org/tcrawley/dynapath/1.0.0/dynapath-1.0.0.jar from central
Retrieving cider/cider-nrepl/0.16.0/cider-nrepl-0.16.0.jar from clojars
Compiling clojurebot.core.evaluator
Compiling clojurebot.core.slack.log
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Compiling clojurebot.core.slack
Compiling clojurebot.core
Created /Users/ray/dev/oss/clojurebot/clojurebot.core/target/uberjar+provided/clojurebot.core-0.1.0-SNAPSHOT.jar
Created /Users/ray/dev/oss/clojurebot/clojurebot.core/target/uberjar/clojurebot.core-0.1.0-SNAPSHOT-standalone.jar
~/dev/oss/clojurebot
~/dev/oss/clojurebot/clojurebot.bootstrap ~/dev/oss/clojurebot
Compiling 1 source files to /Users/ray/dev/oss/clojurebot/clojurebot.bootstrap/target/uberjar/classes
Created /Users/ray/dev/oss/clojurebot/clojurebot.bootstrap/target/uberjar/clojurebot.bootstrap-0.1.0-SNAPSHOT.jar
Created /Users/ray/dev/oss/clojurebot/clojurebot.bootstrap/target/uberjar/clojurebot.bootstrap-0.1.0-SNAPSHOT-standalone.jar
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
token is xyzzyWhatever
Exception in thread "main" java.lang.AssertionError: Assert failed: clj-slack: API URL is not valid. :api-url has to be a valid URL (https://slack.com/api usually), but is nil
(and (string? (:api-url connection)) (and (not (empty? (:api-url connection))) (not (nil? (re-find #"^https?:\/\/" (:api-url connection))))))
        at clj_slack.core$verify_api_url.invokeStatic(core.clj:11)
        at clj_slack.core$verify_api_url.invoke(core.clj:9)
        at clj_slack.core$verify.invokeStatic(core.clj:27)
        at clj_slack.core$verify.invoke(core.clj:24)
        at clj_slack.core$slack_request.invokeStatic(core.clj:80)
        at clj_slack.core$slack_request.invoke(core.clj:76)
        at clj_slack.core$slack_request.invokeStatic(core.clj:78)
        at clj_slack.core$slack_request.invoke(core.clj:76)
        at clj_slack.rtm$connect.invokeStatic(rtm.clj:13)
        at clj_slack.rtm$connect.invoke(rtm.clj:9)
        at slack_rtm.core$internal_connect.invokeStatic(core.clj:148)
        at slack_rtm.core$internal_connect.doInvoke(core.clj:104)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invokeStatic(core.clj:661)
        at clojure.core$apply.invoke(core.clj:652)
        at slack_rtm.core$connect.invokeStatic(core.clj:162)
        at slack_rtm.core$connect.doInvoke(core.clj:161)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at clojurebot.core.slack$start.invokeStatic(slack.clj:47)
        at clojurebot.core.slack$start.invoke(slack.clj:45)
```

where is the Slack URL configured?

**Comment by pjstadig** [comment]
`token` should the the API token from your configured integration, and `log-channel` is a slack channel where the bot will log about what it happening.

The slack URL need not be configured anywhere. The clj-slack library either takes a token, or a map, and when the token is nil it must be assuming that what it got was an (empty) map, so it is complaining about not having a URL.
